### ISSUE TITLE
Create Sections For Post Single Elements

### ISSUE THREAD

**Issue by Asok17** [themebeez/xenial#73]
- [x] Create section for author box and move all related controls into the section.
- [x] Create section for posts navigation and move all related controls into the section.
- [x] Create section for comments and move all related controls into the section.
- [x] Create section for related posts and move all related controls into the section.

**Comment by Asok17** [comment]
All sections are created and respective controls are moved. For all sections, section navigation control has been added in the Post Single section.

**Comment by h1dd3nsn1p3r** [comment]
Ref: #77
